### ISSUE TITLE
1

### ISSUE THREAD

**Issue by fwailiu** [niuwengang/ERASOR_noted#1]
你好，我想问您，您是如何跑自己的数据集通过erasor

**Comment by niuwengang** [comment]
> > 你好，我想问您，您是如何跑自己的数据集通过erasor
> 
> 你成功跑通了erasor吗，我在roslaunch erasor run_erasor.launch target_seq:="05"无反应 请问知道是什么问题吗

修改一下launch文件: 
例如: 
<group if="$(eval arg('target_seq') ==5)">
    <rosparam command="load" file="$(find erasor)/config/seq_05.yaml" />
</group>
<group if="$(eval arg('target_seq') ==7)">
    <rosparam command="load" file="$(find erasor)/config/seq_07.yaml" />
</group>

**Comment by niuwengang** [comment]
> > 你好，我想问您，您是如何跑自己的数据集通过erasor
> 
> 你成功跑通了erasor吗，我在roslaunch erasor run_erasor.launch target_seq:="05"无反应 请问知道是什么问题吗


修改0x为x
```
<group if="$(eval arg('target_seq') ==5)">
    <rosparam command="load" file="$(find erasor)/config/seq_05.yaml" />
</group>
<group if="$(eval arg('target_seq') ==7)">
    <rosparam command="load" file="$(find erasor)/config/seq_07.yaml" />
</group>
```

**Comment by niuwengang** [comment]
> 你好，我想问您，您是如何跑自己的数据集通过erasor

暂时没有试过自己数据集。
